[tool.poetry]
name = "icebreaker"
version = "0.1.0"
description = ""
authors = ["Yoel Monzón <yoelfme@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.1.0"
langchain-openai = "^0.0.2"
black = "^23.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
